name: React Timing Hooks – Build & Test
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}, Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: install locales for integration tests
      run: |
        npm install -g full-icu
        echo "NODE_ICU_DATA=`node-full-icu-path 2>/dev/null`" >> $GITHUB_ENV
      shell: bash
    - name: Lint and unit tests
      run: |
        npm run prettier:check
        npm run test:unit
    - name: Integration tests
      run: |
        npm run build --if-present
        npm run test:integration
      env:
        CI: true
